### ISSUE TITLE
执行MapleStoryApplication的main法和打包后执行 启动服务端-GUI.bat报同一个错[BUG]

### ISSUE THREAD

**Issue by abc706354** [mrzhqiang/ms079#22]
Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:

1) [Guice/MissingConstructor]: No injectable constructor for type LoginServer.

class LoginServer does not have a @Inject annotated constructor or a no-arg constructor.

Requested by:
1  : LoginServer.class(LoginServer.java:30)
     at CharLoginHandler.<init>(CharLoginHandler.java:42)
      \_ for 2nd parameter
     at handling.MapleServerHandler.<init>(MapleServerHandler.java:97)
      \_ for 1st parameter
     at CashShopServer.<init>(CashShopServer.java:35)
      \_ for 3rd parameter
     at ApplicationStarter.<init>(ApplicationStarter.java:65)
      \_ for 5th parameter
     at MapleStoryApplication.<init>(MapleStoryApplication.java:29)
      \_ for 1st parameter
     while locating MapleStoryApplication
2  : LoginServer.class(LoginServer.java:30)
     at CharLoginHandler.<init>(CharLoginHandler.java:42)
      \_ for 2nd parameter
     at handling.MapleServerHandler.<init>(MapleServerHandler.java:97)
      \_ for 1st parameter
     at AuthenticationServer.<init>(AuthenticationServer.java:42)
      \_ for 2nd parameter
     at ApplicationStarter.<init>(ApplicationStarter.java:65)
      \_ for 6th parameter
     at MapleStoryApplication.<init>(MapleStoryApplication.java:29)
      \_ for 1st parameter
     while locating MapleStoryApplication
3  : LoginServer.class(LoginServer.java:30)
     at server.ShutdownServer.<init>(ShutdownServer.java:28)
      \_ for 1st parameter
     at ApplicationStarter.<init>(ApplicationStarter.java:65)
      \_ for 7th parameter
     at MapleStoryApplication.<init>(MapleStoryApplication.java:29)
      \_ for 1st parameter
     while locating MapleStoryApplication

**Comment by mrzhqiang** [comment]
建议用 master 分支第一次提交的版本，并且 jdk 使用 1.7 版本。
目前最新代码都没有经过完整验证。
