### ISSUE TITLE
[BUG]MapleItemInformationProvider中 getItemDate，由于wz下子目录资源（files）未加载，导致部分资源访问会提示空指针。目前影响角色创建时，点击确定无法正常进入游戏

### ISSUE THREAD

**Issue by haojiumeizhaoniliaotian** [mrzhqiang/ms079#26]
**Describe the bug**
异常描述中，写了个死锁的提示，没细看，可能是之前请求的代码逻辑中有事务未正常提交？

(简洁清楚地描述 BUG 是什么)
- 发现异常的【堆栈日志】 
- error updating login statecom.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Optional.<init>(Optional.java:96)
	at java.util.Optional.of(Optional.java:108)
	at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:193)
	at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:190)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at server.MapleItemInformationProvider.getItemData(MapleItemInformationProvider.java:613)
	at server.MapleItemInformationProvider.getEquipStats(MapleItemInformationProvider.java:839)
	at server.MapleItemInformationProvider.getEquipById(MapleItemInformationProvider.java:1180)
	at server.MapleItemInformationProvider.getEquipById(MapleItemInformationProvider.java:1174)
	at handling.login.handler.CharLoginHandler.CreateChar(CharLoginHandler.java:332)
	at handling.MapleServerHandler.handlePacket(MapleServerHandler.java:496)
	at handling.MapleServerHandler.messageReceived(MapleServerHandler.java:398)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:854)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943)
	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:405)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:235)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943)
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:535)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:714)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:668)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:657)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1121)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

- 出现问题的【屏幕截图】
- 可以复现的【详细步骤】
- 你所猜测的【关键因素】 
- 其他相关的【文字描述】

**Expected behavior**

(简洁清楚地描述期望的行为)

1. 正常情况下，应该/不应该 发生的行为
2. 特殊情况下，应该/不应该 发生的行为

**(Optional) About information**

(【可选的】相关信息)

- `OS version`: Windows 10 10.0
- `Java`: Oracle JDK 1.8.0_301
- `DB`: MySQL 5.7.30-log
- `Branchs Tags or Commit Revision`:
  - main
  - develop
  - release-[x.x]
  - tag 1.0
  - revision 1398406e
- `Project version`: 1.0-SNAPSHOT
- `Your customize`: other information

**Comment by haojiumeizhaoniliaotian** [comment]
wzData数据加载问题，在 WzDirectory文件中，attemptParse方法，对目录的处理，增加如下代码：



`private void attemptParse(Path path) {
        try {
            String fileName = path.getFileName().toString();
            if (Files.isDirectory(path)) {
                WzDirectory directory = new WzDirectory(path);
                directory.parse(); // 调整点，新增
                dirs.put(fileName, directory);
            } else {
                Elements data = Jsoup.parse(path.toFile(), "UTF-8").body().children();
                files.put(fileName, new WzFile(fileName, data));
            }
        } catch (IOException e) {
            LOGGER.error("解析 {} 出现问题：{}", path, e);
        }
    }`

**Comment by haojiumeizhaoniliaotian** [comment]
重写了MapleItemInformationProvider 的getItemData 方法，lambda不太熟悉，WzData.ITEM 会遍历两次，有大佬解决这个问题了可以call我一下。


`protected final WzElement<?> getItemData(final int itemId) {
        String idStr = "0" + itemId;
        Optional<ImgdirElement> first = WzData.ITEM.directory().dirStream()
                .map(dir -> dir.findFile(idStr.substring(0, 4))
                        .map(WzFile::content)
                        .orElse(null))
                .filter(Objects::nonNull)
                .findFirst();

        if(!first.isPresent()) {
            first = WzData.ITEM.directory().dirStream()
                    .map(dir -> dir.findFile(idStr.substring(1))
                            .map(WzFile::content)
                            .orElse(null))
                    .filter(Objects::nonNull)
                    .findFirst();
        }

        if(!first.isPresent()){
            first = WzData.CHARACTER.directory().dirStream()
                    .map(dir -> dir.findFile(idStr)
                            .map(WzFile::content)
                            .orElse(null))
                    .filter(Objects::nonNull)
                    .findFirst();
        }
        return first.orElse(null);
    }`

**Comment by mrzhqiang** [comment]
你可以 fork 之后修改相关代码，再提交一个 PR 到本仓库，我会检查一下并合并到本仓库。
