### ISSUE TITLE
客户端启动不了，报errcode-21XXXXXXX

### ISSUE THREAD

**Issue by jcc563768606** [mrzhqiang/ms079#7]
用bat启动不了，报错如下
No suitable driver found for jdbc:mysql://localhost:3307/ms?characterEncoding=UTF-8&autoReconnect=true

很奇怪，我看maven里也有了，应该不需要单独指定jdbc了

自己用debug模式能成功启动服务器
现在卡在客户端进不去了

**Comment by jcc563768606** [comment]
[DB信息] Could not locate the JDBC mysql driver.
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
        at server.Start.startServer(Start.java:163)
        at gui.ZlhssMS.jButton10ActionPerformed(ZlhssMS.java:774)
        at gui.ZlhssMS.access$000(ZlhssMS.java:40)
        at gui.ZlhssMS$1.actionPerformed(ZlhssMS.java:134)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.Component.processMouseEvent(Component.java:6539)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6304)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
        at java.awt.Container.dispatchEventImpl(Container.java:2283)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.UnsupportedOperationException: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3307/ms?characterEncoding=UTF-8&autoReconnect=true
        at database.DatabaseException.<init>(DatabaseException.java:38)
        at database.DatabaseConnection.connectToDB(DatabaseConnection.java:110)
        at database.DatabaseConnection.getConnection(DatabaseConnection.java:32)
        at server.ServerProperties.<clinit>(ServerProperties.java:38)
        ... 40 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3307/ms?characterEncoding=UTF-8&autoReconnect=true
        at java.sql.DriverManager.getConnection(DriverManager.java:689)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at database.DatabaseConnection.connectToDB(DatabaseConnection.java:97)
        ... 42 more

**Comment by jcc563768606** [comment]
![image](https://user-images.githubusercontent.com/11483516/130269951-5a96583c-4b9b-432f-921d-41bd417dbf39.png)

**Comment by jcc563768606** [comment]
调试的时候是能过这一行的

**Comment by jcc563768606** [comment]
我debug模式把服务端起来了，但是客户端还是报错
![image](https://user-images.githubusercontent.com/11483516/130270678-c300cd72-3c0f-4c3a-8e19-744cfead2829.png)

**Comment by jcc563768606** [comment]
079的客户端还有区别的吗？我用的是我自己下载的079

**Comment by jcc563768606** [comment]
win10

**Comment by mrzhqiang** [comment]
README.md 不是提供了客户端吗？
你用你自己下载的，那就自己负责排查客户端错误。

服务端是 maven 打包存在问题，没有把第三方包复制进去。

后续会修复这个问题。

**Comment by jcc563768606** [comment]
主要是嫌阿里云盘下载的太慢了，o(╥﹏╥)o，我还是慢慢下载一下吧

**Comment by mrzhqiang** [comment]
更新了打包方式，bat文件，修复了icon问题

**Comment by hakiGithub** [comment]
你好，我这边使用win7和 README下载的客户端也是有这个错误提示？请问解决了吗？

**Comment by mrzhqiang** [comment]
> 

这个问题是解决了的。你看看是不是你自己驱动的问题。

**Comment by hakiGithub** [comment]
> > 
> 
> 这个问题是解决了的。你看看是不是你自己驱动的问题。

可以了，一开始想在虚拟机的上跑客户端，应该是显卡驱动的问题，在宿主机跑客户端可以启动，请问有没有一些沟通交流的方式？我这边也可以帮忙参与开发

**Comment by mrzhqiang** [comment]
没有微信群QQ群哦，目前没有时间搞这个，搞点私活赚赚钱，等闲下来再弄

**Comment by hakiGithub** [comment]
> 没有微信群QQ群哦，目前没有时间搞这个，搞点私活赚赚钱，等闲下来再弄

OK，那我基于你的develop继续开发了，后面如果开发进度理想，我到时候提个PR帮忙处理一下吧

**Comment by mrzhqiang** [comment]
可以的，欢迎你提 PR。你不像有些人，fork 之后修复了代码也不提交 PR，就只想着拿，没想着给。
